=== hasnamohamed/XML-ITI_9_month/DTD/dtd2.dtd
<!ELEMENT family (grandfather,grandmother)>
<!ELEMENT grandfather (doughter+ ,son+)>
<!ELEMENT grandmother (doughter+, son+)>
<!ATTLIST grandfather name CDATA #REQUIRED age CDATA #REQUIRED>
<!ATTLIST grandmother name CDATA #REQUIRED age CDATA #REQUIRED>
<!ATTLIST son name CDATA #REQUIRED age CDATA #REQUIRED>
<!ATTLIST doughter name CDATA #REQUIRED age CDATA #REQUIRED>
<!ELEMENT son (sonJob?, wife?, sonChild*)>
<!ELEMENT sonJob (#PCDATA) >
<!ELEMENT sonChild (#PCDATA)>
<!ELEMENT wife (#PCDATA)>
<!ELEMENT doughter (doughterJob?, husband?, doughterChild*)>
<!ELEMENT doughterJob (#PCDATA) >
<!ELEMENT husband (#PCDATA)>
<!ELEMENT doughterChild (#PCDATA)>

<!ATTLIST wife name CDATA #IMPLIED >
<!ATTLIST husband name CDATA #IMPLIED>
<!ATTLIST doughterChild name CDATA #IMPLIED >
<!ATTLIST sonJob name CDATA #IMPLIED >
<!ATTLIST doughterJob name CDATA #IMPLIED >
<!ATTLIST sonChild name CDATA #IMPLIED >

=== hasnamohamed/XML-ITI_9_month/DTD/Untitled1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "F:\ITI\XML\Day1\Practice_LAB1\New folder\dtd2.dtd">
<family>
	<grandfather name="" age="">
		<doughter name="" age="">
		<doughterJob></doughterJob>
		<husband></husband>
		<doughterChild></doughterChild>
		</doughter>
		<son name="" age="">
		<sonJob></sonJob>
		<wife></wife>		
		<sonChild></sonChild>
		</son>
	</grandfather>
	<grandmother name="" age="">
		<doughter name="" age="">
		<doughterJob></doughterJob>
		<husband></husband>
		<doughterChild></doughterChild>
		</doughter>
		<son name="" age="">
		<sonJob></sonJob>
		<wife></wife>		
		<sonChild></sonChild>
		</son>
	</grandmother>
</family>
